# -*- coding: utf-8 -*-
senderlinks = {
'3sat' : '3sat', 
'anixe' : 'anixe', 
'ard' : 'das-erste', 
'ardeinsfestival' : 'einsfestival', 
'ardeinsplus' : 'einsplus',
'arte' : 'arte', 
'atv' : 'atv', 
'bay3' : 'bayerisches-fernsehen', 
'bralpha' : 'ard-alpha',
'deluxemusic' : 'deluxe-music',
'disney' : 'disney',
'dmax' : 'dmax', 
'eurosport' : 'eurosport',
'familytv': 'family-tv',
'hr3' : 'hr-fernsehen',
'joiz' : 'joiz',
'kabel1' : 'kabel-eins', 
'kika' : 'kika',
'mdr' : 'mdr', 
'n24' : 'n24',
'ndr' : 'ndr',
'nickelodeon' : 'nickelodeon',
'ntv' : 'n-tv',
'one' : 'one',
'orf1' : 'orf1', 
'orf2' : 'orf2', 
'orf3' : 'orf-iii', 
'phoenix' : 'phoenix',
'pro7' : 'prosieben',
'pro7max' : 'prosiebenmaxx', 
'pro7maxx' : 'prosiebenmaxx',
'rbb' : 'rbb',
'ric' : 'ric',
'rtl' : 'rtl',
'rtl2' : 'rtl2',
'rtlnitro' : 'rtl-nitro',
'rtlnitro' : 'rtl-nitro',
'sat1' : 'sat1',
'sat1gold' : 'sat1gold',
'servustv' :'servustv-deutschland',
'sf2' : 'srf2', 
'sixx' : 'sixx',
'sport1' : 'sport1',
'srtl' : 'superrtl', 
'stv' :'servustv-deutschland',
'stva': 'servustv',       # Österreich manuell umbenannt
'sw3' : 'swr-fernsehen',
'tagesschau24' : 'tagesschau24',
'tele5' : 'tele5', 
'tv24' :'tv24',
'ukbbc': 'UK-bbc',
'ukbbc2': 'UK-bbc2',
'ukbbc3': 'UK-bbc3',
'ukbbc4': 'UK-bbc4',
'ukfilm4': 'UK-film4',
'ukitv': 'UK-itv',
'ukitv2': 'UK-itv2',
'ukitv3': 'UK-itv3',
'uswabc': 'us-wabc',
'uswnbc': 'us-wnbc',
'uswnyw': 'us-wnyw',
'viva': 'comedy-central',
'vox' : 'vox',
'wdr' : 'wdr',
'zdf' : 'zdf',
'zdf_neo' : 'zdf_neo',
'zdfinfo' : 'zdfinfo',
'zdfkultur' : 'zdf-kultur',
'zdfneo' : 'zdf_neo'
}
