# -*- coding: utf-8 -*-
serieslinks = {
# Seriename laut Datei    , Serienname bei Fernsehserien.de
'Braquo F 2009': 'braquo-das-gesetz-war-gestern',
'Bull': 'Bull-2016',
'Ein Mountie in Chicago Kan': 'Ein-Mountie-in-Chicago',
'Einstein': 'einstein-2015' ,
'Fringe':'fringe-grenzfaelle-des-fbi',
'Game Of Thrones Das Lied von Eis und Feuer':'game-of-thrones', 
'Grey s Anatomy Die jungen Aerzte':'greys-anatomy',
'Hell on Wheels USA 2014': 'hell-on-wheels', 
'Hell on Wheels USA 2015': 'hell-on-wheels', 
'Hooten the Lady': 'Hooten-and-the-Lady',
'In Plain Sight': 'in-plain-sight-in-der-schusslinie',
'In Plain Sight USA 2009': 'in-plain-sight-in-der-schusslinie',
'Jordskott Die Rache des Waldes II': 'jordskott',
'Justified Krimiserie': 'justified',
'K C  Undercover': 'kc-undercover',
'Lewis': 'lewis-der-oxford-krimi',
'Line of Duty Cops unter Verdacht': 'Line-of-Duty',
'Marvel s Agents of S H I E L D':'the-agents-of-s-h-i-e-l-d',
'Marvel s Agents of S H I E L D': 'Marvels-Agents-of-Shield',
'Medium     Nichts bleibt verborgen USA 2009': 'medium-nichts-bleibt-verborgen',
'Medium     Nichts bleibt verborgen USA 2010': 'medium-nichts-bleibt-verborgen',
'Medium     Nichts bleibt verborgen USA 2011': 'medium-nichts-bleibt-verborgen',
'New Tricks - Die Krimispezialisten': 'new-tricks',
'New Tricks     Die Krimispezialisten': 'new-tricks',
'Once Upon A Time Es war einmal   ': 'Once-Upon-A-Time-Es-war-einmal',
'Rosewood USA 2016': 'Rosewood',
'Rosewood USA 2017': 'Rosewood',
'Stalker USA 2014': 'Stalker',
'Sylvia s Cats': 'Sylvias-Cats',
'The Big Bang Theory' : 'the-big-bang-theory',
'The Shield - Gesetz der Gewalt': 'the-shield',
'The Simpsons' : 'die-simpsons',
'The Vampire Diaries':'Vampire-Diaries',
'This Is Us Das ist Leben':'This-Is-Us',
'Top of the Lake China Girl': 'top-of-the-lake',
'Without a Trace - Spurlos verschwunden': 'without-a-trace',
'Zoo The Final Battle': 'zoo'
}
               #to be continued...
